#!/usr/bin/python3

import csv
import os

SOURCE_CSV_FILENAME = "SolarNoon_2024.csv"
HEADER_FILENAME = "solar_noon.h"


def time_to_int( time:str ) -> int:
	sections: list[str] = time.split(":")
	# print(sections)
	hours: int = int(sections[0])
	min: int = int(sections[1])
	return min + (60 * hours)

print(f"Opening source file '{SOURCE_CSV_FILENAME}'...")
with open(SOURCE_CSV_FILENAME) as csvfile:
	with open(HEADER_FILENAME, "w") as outfile:
		data = csv.reader(csvfile)

		# Write hardcoded section to outfile.
		outfile.write("// This file was auto-generated by SolarNoonHeaderMaker.py!\n")
		outfile.write("// It is preferred to make changes to the source file \"" + SOURCE_CSV_FILENAME + "\" instead of here.\n\n")

		outfile.write("// Solar Noon in minutes since midnight, indexed by day-of-year.\n")
		outfile.write("const int SOLAR_NOON_MINUTES[] = {")

		num_days: int = 0

		for row in data: # only process the first cell in each row
			time: str = row[0]
			# print(time)
			# print(time_to_int(time))
			num_days += 1

			if( num_days > 1 ):
				outfile.write(",")
			
			outfile.write(str(time_to_int(time)) )
 
		outfile.write("}; \n")
		print(f"Wrote {num_days} days of data to '{HEADER_FILENAME}'")

